
<div id="livechat">
<div style="display:flex; justify-content: space-around; <?php echo Mage::getStoreConfig('livechat/general/license') > 0 ? 'display: none;':'' ?>" >
	<div>
		<div style="display: flex; flex-direction: column; align-items: center; margin-bottom: 40px;">
			<div style="display: flex; flex-direction: row; align-items: center;">
				<div class="livechat_logo2"></div>
			</div>
			<div id="login_form">
				<div class="progress-button hidden">
					Saving...
				</div>
				<div>				
					<iframe id="login-with-livechat" src="https://addons.livechatinc.com/sign-in-with-livechat"> </iframe>
				</div>
			</div>
			<div class="or-delimiter">or</div>
			<div id="livechat_link" style="font-size: 15px; margin-top:4px;">
				<a href="https://my.livechatinc.com/signup?utm_source=magento.com&utm_medium=integration&utm_campaign=magento_integration" target="_blank">create an account</a>
			</div>
		</div>
	</div>
	<div style="text-align: center;">
		<div class="livechat_screenshot"></div>
		<p style="font-size:16px;">Check out our apps for <a href="https://www.livechatinc.com/applications/?utm_source=magento.com&amp;utm_medium=integration&amp;utm_campaign=magento_integration" target="_blank">desktop or mobile!</a></p>
	</div>
	
</div>

<!-- Already have an account -->
<div id="livechat_already_have" style="<?php echo Mage::getStoreConfig('livechat/general/license') < 0 ? 'display: none;':'' ?>">

	<form method="post" action="<?php echo $this->getUrl('*/*/post'); ?>">
		<?php $salt = Mage::getSingleton('core/session')->getFormKey();?>
		<input name="form_key" type="hidden" value="<?php echo $salt ?>" /> 
		<input name="livechat_license_number" type="hidden" id="livechat_license_number" value="<?php echo Mage::getStoreConfig('livechat/general/license') ?>">
		<input name="livechat_login" type="hidden" id="livechat_login" value="<?php echo Mage::getStoreConfig('livechat/general/login') ?>">
</div>
			
		
		<?php if (Mage::getStoreConfig('livechat/general/license') > 0): ?>
		
	<div style="display: flex; justify-content: space-around; align-items: center;">
		<div style="display: flex; justify-content: space-around; align-items: center; flex-direction: column;">
			<table cellspacing="0" class="form-list">
					<tbody>
						<tr>
							<td colspan="2">
								<div class="messages success-msg">Your LiveChat is now ready!</div>
							</td>
						</tr>
						<tr>
							<td colspan="2">
								<div class="messages note-msg" style="margin-bottom: -4px;">You are now rocking chat window from your <?php echo Mage::getStoreConfig('livechat/general/login') ?> account.</div>
							</td>
						</tr>
						<tr>
							<td colspan="2">
								
							</td>
						</tr>
						<tr>
							<td class="label tooltip"><label>Track your customers cart <span class="question_mark"></span> :</label><span class="tooltiptext3">See what products are in your customer's cart and check their total value (this value is updated every 20 seconds).</span></td>
							<td class="value">
								<select name="livechat_cart" class="select">
									<option value="Yes" <?php echo Mage::getStoreConfig('livechat/general/cart') === 'Yes' ? ' selected="selected"' : '';?>>Yes</option>
									<option value="No" <?php echo Mage::getStoreConfig('livechat/general/cart') === 'No' ? ' selected="selected"' : '';?>>No</option>
								</select>
							</td>
						</tr>
						<tr>
							<td>
								
							</td>
						</tr>
						<tr>
							<td class="label tooltip"><label>Hide chat window on mobile <span class="question_mark"></span> :</label><span class="tooltiptext2">Hide chat window for visitors browsing your store from mobile.</span></td>
							<td class="value">
								<select name="livechat_mobile" class="select">
									<option value="Yes" <?php echo Mage::getStoreConfig('livechat/general/mobile') === 'Yes' ? ' selected="selected"' : '';?>>Yes</option>
									<option value="No" <?php echo Mage::getStoreConfig('livechat/general/mobile') === 'No' ? ' selected="selected"' : '';?>>No</option>
								</select>
							</td>
						</tr>
						<tr>
							<td>
								
							</td>
						</tr>
						<tr>
							<td colspan="2">
								<button title="Save" type="button" class="scalable save" onclick="jQuery('#livechat_already_have form').submit()" style="float:right; margin-top: 16px;"><span>Save</span></button>					
							</td>
						</tr>
					</tbody>
				</table>
		
		</div>
		<div style="text-align: center;">
			<div class="livechat_screenshot"></div>
			    
			<p>Use our <a href="https://my.livechatinc.com?utm_source=magento.com&amp;utm_medium=integration&amp;utm_campaign=magento_integration" target="_blank">web application</a> or download <a href="https://www.livechatinc.com/applications/?utm_source=magento.com&amp;utm_medium=integration&amp;utm_campaign=magento_integration" target="_blank">the app</a> for desktop or mobile!</p>
		</div>
	</div>

	<p>Need help? Check out our <a href="http://www.livechatinc.com/en/addons_and_extras/magento/integration_tutorial/?utm_source=magento.com&amp;utm_medium=integration&amp;utm_campaign=magento_integration" target="_blank">LiveChat for Magento integration tutorial</a>.</p>
	<p class="reset-settings">Something went wrong? <a class="reset-settings" href="<?php echo Mage::helper('adminhtml')->getUrl('*/*/reset')?>" id="reset_settings">Click here</a> to reset settings!</p>
	<?php endif; ?>

	</form>
</div>
<script src="<?php echo $this->getSkinUrl('js/livechat') ?>/livechat.js" type="text/javascript"></script>